scope1: "Scope.APP"{
component2: "Scope.APP"{
factory3: "📥 AsyncContainer"{
    shape: class
}

factory4: "🏭 ConnectorProto_RequestData_BattleId___BattleId_"{
    shape: class
    "SessionManager_T_()": ""
}

factory5: "🏭 list"{
    shape: class
    "IoC.db()": ""
}

factory6: "🏭 Ⓘ ClientProto"{
    shape: class
    "BattleAPIClient()": ""
    ConnectorProto_RequestData_BattleId___BattleId_
    AppConfig
}

factory7: "🏭 Ⓘ PlayersMapper"{
    shape: class
    "PlayerMemoryMapper()": ""
    list
}

factory8: "📥 AppConfig"{
    shape: class
}

factory9: "🏭 None"{
    shape: class
    "IoC.db()": ""
}

}

}
scope1.component2.factory4 --> scope1.component2.factory6
scope1.component2.factory8 --> scope1.component2.factory6
scope1.component2.factory5 --> scope1.component2.factory7
scope10: "Scope.REQUEST"{
component11: "Scope.REQUEST"{
factory12: "📥 AsyncContainer"{
    shape: class
}

factory13: "🏭 AsyncInteractor_CreateHeroDTO__NoneType_"{
    shape: class
    "InitHeroInteractor()": ""
    PlayersMapper
    HeroFactory
}

factory14: "🏭 HeroFactory"{
    shape: class
    "HeroFactory()": ""
}

factory15: "🏭 AsyncInteractor_StartBattleDTO__BattleId_"{
    shape: class
    "StartBattleInteractor()": ""
    ClientProto
    PlayersMapper
}

factory16: "🏭 Interactor_CreatePlayer__Player_"{
    shape: class
    "NewPlayerInteractor()": ""
    PlayersMapper
}

factory17: "🏭 Interactor_GetPlayersQuery__list_Player__"{
    shape: class
    "ReadPlayersInteractor()": ""
    PlayersMapper
}

factory18: "🏭 Interactor_GetPlayerQuery__Player_"{
    shape: class
    "ReadPlayerInteractor()": ""
    PlayersMapper
}

}

}
scope1.component2.factory7 --> scope10.component11.factory13
scope10.component11.factory14 --> scope10.component11.factory13
scope1.component2.factory6 --> scope10.component11.factory15
scope1.component2.factory7 --> scope10.component11.factory15
scope1.component2.factory7 --> scope10.component11.factory16
scope1.component2.factory7 --> scope10.component11.factory17
scope1.component2.factory7 --> scope10.component11.factory18
