scope1: "Scope.APP"{
component2: "Scope.APP"{
factory3: "📥 AsyncContainer"{
    shape: class
}

factory4: "🏭 ConnectorProto_RequestData_BattleStarted___BattleStarted_"{
    shape: class
    "SessionManager_T_()": ""
}

factory5: "🏭 Ⓘ Hasher"{
    shape: class
    "HasherImpl()": ""
    AppConfig
}

factory6: "🏭 defaultdict"{
    shape: class
    "IoC.db()": ""
}

factory7: "🏭 Ⓘ ClientProto"{
    shape: class
    "BattleAPIClient()": ""
    ConnectorProto_RequestData_BattleStarted___BattleStarted_
    AppConfig
}

factory8: "🏭 BattleKeysGateway"{
    shape: class
    "BattleKeysGateway()": ""
}

factory9: "🏭 Ⓘ PlayersMapper"{
    shape: class
    "PlayerMemoryMapper()": ""
    defaultdict
}

factory10: "🏭 NullSuiteFactory"{
    shape: class
    "NullSuiteFactory()": ""
}

factory11: "🏭 CentralShopFactory"{
    shape: class
    "CentralShopFactory()": ""
    NullSuiteFactory
}

factory12: "🏭 Shop"{
    shape: class
    "IoC.shop()": ""
    CentralShopFactory
}

factory13: "📥 dict_str__SessionData_"{
    shape: class
}

factory14: "📥 AppConfig"{
    shape: class
}

factory15: "🏭 None"{
    shape: class
    "IoC.db()": ""
}

}

}
scope1.component2.factory14 --> scope1.component2.factory5
scope1.component2.factory4 --> scope1.component2.factory7
scope1.component2.factory14 --> scope1.component2.factory7
scope1.component2.factory6 --> scope1.component2.factory9
scope1.component2.factory10 --> scope1.component2.factory11
scope1.component2.factory11 --> scope1.component2.factory12
scope16: "Scope.SESSION"{
component17: "Scope.SESSION"{
factory18: "📥 AsyncContainer"{
    shape: class
}

factory19: "📥 WebSocket"{
    shape: class
}

}

}
scope20: "Scope.REQUEST"{
component21: "Scope.REQUEST"{
factory22: "📥 AsyncContainer"{
    shape: class
}

factory23: "🏭 AsyncInteractor_CreateHeroDTO__NoneType_"{
    shape: class
    "InitHeroInteractor()": ""
    PlayersMapper
    HeroFactory
    IDProvider
}

factory24: "🏭 AsyncInteractor_BattleResult__NoneType_"{
    shape: class
    "TakeEventInteractor()": ""
    BattleResultMapper
    StatisticsWriter
}

factory25: "🏭 Ⓘ BattleResultMapper"{
    shape: class
    "BattleResultMemoryMapper()": ""
    defaultdict
}

factory26: "🏭 Ⓘ RSessionIDManager"{
    shape: class
    "RSessionIDManagerImpl()": ""
    AppConfig
    Hasher
    dict_str__SessionData_
}

factory27: "🏭 Interactor_UserLoginDTO__User_"{
    shape: class
    "UserLoginInteractor()": ""
    UserMapper
    RSessionIDManager
    Hasher
}

factory28: "🏭 Interactor_UserRegisterDTO__User_"{
    shape: class
    "UserRegisterInteractor()": ""
    UserMapper
    PlayersMapper
    RSessionIDManager
    Hasher
}

factory29: "🏭 Interactor_BattleResultsQuery__list_BattleResult__"{
    shape: class
    "BattleResultsInteractor()": ""
    BattleResultMapper
}

factory30: "🏭 Ⓘ UserMapper"{
    shape: class
    "UserMemoryMapper()": ""
    defaultdict
}

factory31: "🏭 HeroFactory"{
    shape: class
    "HeroFactory()": ""
}

factory32: "🏭 GetKeyInteractor"{
    shape: class
    "GetKeyInteractor()": ""
    BattleKeysGateway
    IDProvider
}

factory33: "🏭 AsyncInteractor_StartBattleDTO__BattleId_"{
    shape: class
    "StartBattleInteractor()": ""
    ClientProto
    PlayersMapper
    BattleKeysGateway
    WaitingBattleGatewayProto
    IDProvider
}

factory34: "🏭 Interactor_CreatePlayer__Player_"{
    shape: class
    "NewPlayerInteractor()": ""
    PlayersMapper
    RSessionIDManager
    IDProvider
}

factory35: "🏭 Interactor_GetPlayersQuery__list_Player__"{
    shape: class
    "ReadPlayersInteractor()": ""
    PlayersMapper
}

factory36: "🏭 Interactor_GetPlayerQuery__Player_"{
    shape: class
    "ReadPlayerInteractor()": ""
    PlayersMapper
}

factory37: "🏭 Interactor_int__PlayersHero_"{
    shape: class
    "EquipInteractor()": ""
    IDProvider
    PlayersMapper
}

factory38: "🏭 Interactor_ShopSearch__list_Good__"{
    shape: class
    "SearchOffer()": ""
    Shop
}

factory39: "🏭 AsyncInteractor_BuyCommand__Player_"{
    shape: class
    "BuyInteractor()": ""
    Shop
    PlayersMapper
    IDProvider
    StatisticsWriter
}

factory40: "🏭 Interactor_HeroClass__NoneType_"{
    shape: class
    "WaitForOpponentInteractor()": ""
    PlayersMapper
    IDProvider
    WaitingBattleGatewayProto
}

factory41: "🏭 Ⓘ WaitingBattleDTOReader"{
    shape: class
    "WaitingBattleGateway()": ""
    defaultdict
}

factory42: "🏭 Ⓘ StatisticsWriter"{
    shape: class
    "IoC.stats_writer()": ""
    AppConfig
}

factory43: "🏭 Ⓘ IDProvider"{
    shape: class
    "IoC.auth_provider()": ""
    dict_str__SessionData_
    Request
}



factory46: "📥 Request"{
    shape: class
}

}

}
scope1.component2.factory9 --> scope20.component21.factory23
scope20.component21.factory31 --> scope20.component21.factory23
scope20.component21.factory43 --> scope20.component21.factory23
scope20.component21.factory25 --> scope20.component21.factory24
scope20.component21.factory42 --> scope20.component21.factory24
scope1.component2.factory6 --> scope20.component21.factory25
scope1.component2.factory14 --> scope20.component21.factory26
scope1.component2.factory5 --> scope20.component21.factory26
scope1.component2.factory13 --> scope20.component21.factory26
scope20.component21.factory30 --> scope20.component21.factory27
scope20.component21.factory26 --> scope20.component21.factory27
scope1.component2.factory5 --> scope20.component21.factory27
scope20.component21.factory30 --> scope20.component21.factory28
scope1.component2.factory9 --> scope20.component21.factory28
scope20.component21.factory26 --> scope20.component21.factory28
scope1.component2.factory5 --> scope20.component21.factory28
scope20.component21.factory25 --> scope20.component21.factory29
scope1.component2.factory6 --> scope20.component21.factory30
scope1.component2.factory8 --> scope20.component21.factory32
scope20.component21.factory43 --> scope20.component21.factory32
scope1.component2.factory7 --> scope20.component21.factory33
scope1.component2.factory9 --> scope20.component21.factory33
scope1.component2.factory8 --> scope20.component21.factory33
scope20.component21.factory41 --> scope20.component21.factory33: 🔗 WaitingBattleGatewayProto
scope20.component21.factory43 --> scope20.component21.factory33
scope1.component2.factory9 --> scope20.component21.factory34
scope20.component21.factory26 --> scope20.component21.factory34
scope20.component21.factory43 --> scope20.component21.factory34
scope1.component2.factory9 --> scope20.component21.factory35
scope1.component2.factory9 --> scope20.component21.factory36
scope20.component21.factory43 --> scope20.component21.factory37
scope1.component2.factory9 --> scope20.component21.factory37
scope1.component2.factory12 --> scope20.component21.factory38
scope1.component2.factory12 --> scope20.component21.factory39
scope1.component2.factory9 --> scope20.component21.factory39
scope20.component21.factory43 --> scope20.component21.factory39
scope20.component21.factory42 --> scope20.component21.factory39
scope1.component2.factory9 --> scope20.component21.factory40
scope20.component21.factory43 --> scope20.component21.factory40
scope20.component21.factory41 --> scope20.component21.factory40: 🔗 WaitingBattleGatewayProto
scope1.component2.factory6 --> scope20.component21.factory41
scope1.component2.factory14 --> scope20.component21.factory42
scope1.component2.factory13 --> scope20.component21.factory43
scope20.component21.factory46 --> scope20.component21.factory43
